package controller;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import model.SceneName;
import view.SceneManager;

/**
 * The Controller related to the mainMenu.fxml GUI.
 *
 */
public final class UIControllerMainMenu {

    @FXML
    private Button btNewgame, btSettings, btProfile, btExit;

    /**
     * The handler for the click events generated by the button.
     */
    @FXML
    public void btNewGameOnClickHandler() {
        SceneManager.INSTANCE.switchScene(SceneName.MATCH_SETTINGS);
    }

    /**
     *  The handler for the click events generated by the button.
     */
    @FXML
    public void btSettingsOnClickHandler() {
        System.out.println("Settings button clicked\n ");
    }

    /**
     *  The handler for the click events generated by the button.
     */
    @FXML
    public void btProfileOnClickHandler() {
        System.out.println("Profile button clicked\n ");
    }

    /**
     *  The handler for the click events generated by the button.
     */
    @FXML
    public void btExitOnClickHandler() {
        System.out.println("Closing application. . .\n ");
        System.exit(0);
    }

}
