package controller;

import javafx.scene.control.TextArea;
import java.util.Set;
import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.CheckBox;
import javafx.scene.control.ChoiceBox;
import model.MatchManager;
import model.MatchManagerImpl;
import model.Player;
import model.PlayerAI;
import model.ProfileLoader;
import model.SceneName;
import model.WinCondition;
import view.SceneManager;


/**
 *  The Controller related to the matchSettings.fxml GUI.
 *
 */
public final class UIControllerMatchSettings {

    private final Set<Player> profiles = new ProfileLoader().load();

    @FXML
    private Button buttonBack, buttonStart;
    @FXML
    private ChoiceBox<String> choiceboxPlayer1, choiceboxPlayer2, choiceboxGamemode;
    @FXML
    private CheckBox checkboxAI;
    @FXML
    private TextArea textareaDescription;

    /**
     * this method is called automatically when loading the fxml layout. It sets the initial state of the UI
     */
    public void initialize() {
        for (Player p : profiles) {
            choiceboxPlayer1.setStyle("-fx-font: 18px \"Serif\";");
            choiceboxPlayer2.setStyle("-fx-font: 18px \"Serif\";");
            choiceboxGamemode.setStyle("-fx-font: 18px \"Serif\";");
            choiceboxPlayer1.getItems().add(p.getName());
            choiceboxPlayer2.getItems().add(p.getName());
        }
        for (WinCondition wc : WinCondition.values()) {
            choiceboxGamemode.getItems().add(wc.getName());
        }
        choiceboxPlayer1.getSelectionModel().selectFirst();
        choiceboxPlayer2.getSelectionModel().selectFirst();
        choiceboxGamemode.getSelectionModel().selectFirst();
        choiceboxGamemode.getSelectionModel().selectedItemProperty().addListener(new ChangeListener<String>() {
            @Override
            public void changed(final ObservableValue<? extends String> observable, final String oldValue, final String newValue) {
                updateTextareaDescription(WinCondition.getWinConditionFromName(newValue).getDescription());
            }
        });
        this.updateTextareaDescription(WinCondition.ALL_ENEMY_SHIPS_SUNK.getDescription());
    }

    /**
     *  The handler for the click events generated by the button.
     */
    @FXML
    public void buttonBack() {
        SceneManager.INSTANCE.switchScene(SceneName.MAIN);
    }

    /**
     *  The handler for the click events generated by the button.
     */
    @FXML
    public void buttonStart() {
        Player p1, p2;
        p1 = getSelectedPlayer(choiceboxPlayer1);
        if (checkboxAI.isSelected()) {
            p2 = new PlayerAI("AI");
        } else {
            p2 = getSelectedPlayer(choiceboxPlayer2);
        }
        MatchManager gm = new MatchManagerImpl(Set.of(p1, p2), WinCondition.getWinConditionFromName(choiceboxGamemode.getSelectionModel().getSelectedItem()));
        // START THE MATCH WITH SELECTED SETTINGS
        //gm.start();
    }

    /**
     *  The handler for the click events generated by the checkbox.
     */
    @FXML
    public void checkboxAI() {
        choiceboxPlayer2.setDisable(!choiceboxPlayer2.isDisabled());
    }

    private void updateTextareaDescription(final String text) {
        this.textareaDescription.setText(text);
    }

    private Player getSelectedPlayer(final ChoiceBox<String> cb) {
        return profiles.stream()
                .filter(x -> x.getName().equals(cb.getSelectionModel().getSelectedItem()))
                .reduce((a, b) -> {
                    throw new IllegalStateException("Multiple profiles with same name: " + a + ", " + b);
                })
                .get();
    }

}
