package controller.ui;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import model.enums.SceneName;
import view.SceneManager;

/**
 * The Controller related to the mainMenu.fxml GUI.
 *
 */
public final class MainMenu {

    @FXML
    private Button buttonNewGame, buttonSettings, buttonProfile, buttonExit;

    /**
     * The handler for the click events generated by the button.
     */
    @FXML
    public void buttonNewGame() {
        SceneManager.INSTANCE.switchScene(SceneName.MATCH_SETTINGS);
    }

    /**
     *  The handler for the click events generated by the button.
     */
    @FXML
    public void buttonSettings() {
        System.out.println("Settings button clicked\n ");
    }

    /**
     *  The handler for the click events generated by the button.
     */
    @FXML
    public void buttonProfile() {
        System.out.println("Profile button clicked\n ");
    }

    /**
     *  The handler for the click events generated by the button.
     */
    @FXML
    public void buttonExit() {
        System.exit(0);
    }

}
