package controller.ui;

import javafx.scene.control.TextArea;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashSet;
import java.util.Optional;
import controller.players.AccountManager;
import controller.players.AccountOperation;
import controller.players.Player;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.CheckBox;
import javafx.scene.control.ChoiceBox;
import model.enums.SceneName;
import model.enums.DialogType;
import model.enums.GameMode;
import model.enums.PlayerType;
import model.match.MatchManager;
import model.match.MatchManagerImpl;
import view.SceneManager;
import view.dialog.DialogBuilder;
import view.dialog.GenericDialog;


/**
 *  The Controller related to the matchSettings.fxml GUI.
 *
 */
public final class MatchSettings {

    private final DialogBuilder dialog = new GenericDialog();
    private final AccountManager accountManager = new AccountOperation();
    private final Collection<String> usernames = new ArrayList<String>();
    private GameMode selectedWinCondition = GameMode.CLASSIC;

    @FXML
    private Button buttonBack, buttonStart;
    @FXML
    private ChoiceBox<String> choiceboxPlayer1, choiceboxPlayer2;
    @FXML
    private ChoiceBox<GameMode> choiceboxGameMode;
    @FXML
    private CheckBox checkboxAI;
    @FXML
    private TextArea textareaDescription;

    /**
     * this method is called automatically when loading the fxml layout. It sets the initial state of the UI
     */
    public void initialize() {
        //TODO remove null check once loader is stable
        if (accountManager.getAllUsername() != null) {
            usernames.addAll(accountManager.getAllUsername());
        }
        //TODO remove test usernames
        usernames.add("temptest1");
        usernames.add("temptest2");
        initChoiceBox(choiceboxPlayer1, usernames);
        initChoiceBox(choiceboxPlayer2, usernames);
        initChoiceBox(choiceboxGameMode, Arrays.asList(GameMode.values()));
        textareaDescription.setText(selectedWinCondition.getDescription()); 
    }

    /**
     *  The handler for the click events generated by the button.
     */
    @FXML
    public void buttonStart() {
        boolean aiPlayer = checkboxAI.isSelected();
        String username1 = getSelectedItem(choiceboxPlayer1);
        String username2 = aiPlayer ? null : getSelectedItem(choiceboxPlayer2);
        if (arePlayersValid(username1, username2, aiPlayer)) {
            this.startMatch(username1, username2, aiPlayer ? PlayerType.ARTIFICIAL : PlayerType.HUMAN);
        }
        
    }

    /**
     *  The handler for the click events generated by the checkbox.
     */
    @FXML
    public void checkboxAI() {
        choiceboxPlayer2.setDisable(!choiceboxPlayer2.isDisabled());
    }

    /**
     *  The handler for the click events generated by the button.
     */
    @FXML
    public void buttonBack() {
        SceneManager.INSTANCE.switchScene(SceneName.MAIN);
    }

    private <T> void initChoiceBox(final ChoiceBox<T> cb, final Collection<T> c) {
        c.forEach(x -> cb.getItems().add(x));
        cb.setStyle("-fx-font: 18px \"Serif\";");
        if (cb.equals(choiceboxGameMode)) {
            cb.getSelectionModel().selectFirst();
            cb.getSelectionModel().selectedItemProperty().addListener((x, y, z) -> {
                selectedWinCondition = getSelectedItem(choiceboxGameMode);
                textareaDescription.setText(selectedWinCondition.getDescription());
            });
        } else {
            cb.getSelectionModel().selectedItemProperty().addListener((x, y, z) -> {
                if (getSelectedItem(cb) != null) {
                    checkCredentials(cb, (String) getSelectedItem(cb));
                }
            });
        }
    }

    private <T> void checkCredentials(final ChoiceBox<T> cb, final String username) {
        final Optional<String> password = dialog.launch(DialogType.LOGIN, "Login", "Insert password for user \"" + username + "\"", null);
        final boolean isLoginValid = ((password.isPresent()) ?  accountManager.logInAccount(username, password.get()) : false);
        if (isLoginValid) {
            dialog.launch(DialogType.INFORMATION, "Login", "Login successful!", null);
        } else {
            cb.getSelectionModel().clearSelection();
            dialog.launch(DialogType.ERROR, "Login", "Invalid account credentials!", null);
        }
    }

    private void startMatch(final String username1, final String username2, PlayerType playerType) {
        MatchManager gm = new MatchManagerImpl(username1, username2, playerType, selectedWinCondition);
        String winner = gm.startNewMatch();
        dialog.launch(DialogType.INFORMATION, "Match over!", "Player " + winner + " won the match!\nPress ok to go back to menu.", null);
        SceneManager.INSTANCE.switchScene(SceneName.MAIN);
    }

    private <T> T getSelectedItem(final ChoiceBox<T> cb) {
        return cb.getSelectionModel().getSelectedItem();
    }

    private boolean arePlayersValid(final String username1, final String username2, final boolean aiPlayer) {
        if (username1 == null || (username2 == null && !aiPlayer)) {
            dialog.launch(DialogType.ERROR, "Error!", "Some players have no profile selected!\nChange your selection and try again.", null);
        } else if (username1.equals(username2)) {
            dialog.launch(DialogType.ERROR, "Error!", "Player1 and Player2 cannot be the same!\nChange your selection and try again.", null);
        } else {
            return true;
        }
        return false;
    }

}
