package match_settings;

import java.util.Iterator;
import java.util.Set;
import controllers.GameManager;
import controllers.GameManagerImpl;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.CheckBox;
import javafx.scene.control.ChoiceBox;
import model.Player;
import model.PlayerAI;
import model.ProfileLoader;
import model.SceneName;
import view.ViewManager;


/**
 *  The Controller related to the gameModeSelection.fxml GUI.
 *
 */
public final class UIControllerMatchSettings {
    
    Set<Player> profiles = new ProfileLoader().load();
    
    @FXML
    private Button btBtmm;
    @FXML
    private Button btStrt;
    @FXML
    private ChoiceBox<String> choicebPlayer1;
    @FXML
    private ChoiceBox<String> choicebPlayer2;
    @FXML
    private CheckBox checkbAI;
    
    public void initialize() {
        Iterator<Player> it = profiles.iterator();
        while(it.hasNext()) {
            String next = it.next().getName();
            choicebPlayer1.getItems().add(next);
            choicebPlayer2.getItems().add(next);
        }
        choicebPlayer1.getSelectionModel().selectFirst();
        choicebPlayer2.getSelectionModel().selectFirst();
    }

    /**
     *  The handler for the click events generated by the button.
     */
    @FXML
    public void btBtmmOnClickHandler() {
        System.out.println("\"Back To Main Menu\" button clicked\n ");
        ViewManager.getInstance().switchScene(SceneName.MAIN);
    }

    /**
     *  The handler for the click events generated by the button.
     */
    @FXML
    public void btStrtOnClickHandler() {
        System.out.println("\"Start Game\" button clicked\n ");
        // TODO have this handler call a function to deal with gamemanager rather than doing it itself
        Player p1,p2;
        p1 = profiles.stream()
            .filter(x -> x.getName().equals(choicebPlayer1.getSelectionModel().getSelectedItem()))
            .reduce((a, b) -> {
                throw new IllegalStateException("Multiple profiles with same name: " + a + ", " + b);
            })
            .get();
        if(checkbAI.isSelected()) {
            p2 = new PlayerAI("AI");
        } else {
            p2 = profiles.stream()
                .filter(x -> x.getName().equals(choicebPlayer2.getSelectionModel().getSelectedItem()))
                .reduce((a, b) -> {
                    throw new IllegalStateException("Multiple profiles with same name: " + a + ", " + b);
                })
                .get();
        }
        final GameManager gm = new GameManagerImpl(p1,p2);
        //gm.start();
    }
    
    /**
     *  The handler for the click events generated by the button.
     */
    @FXML
    public void checkbAIonClickHandler() {
        System.out.println("checkbox clicked\n ");
        choicebPlayer2.setDisable(!choicebPlayer2.isDisabled());
    }

}
