package main_menu;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import model.SceneName;
import view.ViewManager;

/**
 * The Controller related to the mainMenu.fxml GUI.
 *
 */
public final class UIControllerMainMenu {

    @FXML
    private Button btNewg;
    @FXML
    private Button btSett;
    @FXML
    private Button btProf; 
    @FXML
    private Button btExit;

    /**
     * The handler for the click events generated by the button.
     */
    @FXML
    public void btNewgOnClickHandler() {
        System.out.println("NewGame button clicked\n ");
        ViewManager.getInstance().switchScene(SceneName.GAMEMODE_SELECTION);
    }

    /**
     *  The handler for the click events generated by the button.
     */
    @FXML
    public void btSettOnClickHandler() {
        System.out.println("Settings button clicked\n ");
    }

    /**
     *  The handler for the click events generated by the button.
     */
    @FXML
    public void btProfOnClickHandler() {
        System.out.println("Profile button clicked\n ");
    }

    /**
     *  The handler for the click events generated by the button.
     */
    @FXML
    public void btExitOnClickHandler() {
        System.out.println("Exit button clicked\n ");
        System.out.println("Exiting...\n ");
        System.exit(0);
    }

}
